"use strick";
import timer from "./modules/timer";
import menu from "./modules/menu";
import modal from "./modules/modal";
import validate from "./modules/validate";
import tabs from "./modules/tabs";
import slider from "./modules/slider";
import calc from "./modules/calc";
import getSend from "./modules/send";
import sendForm from "./modules/sendForm";

timer("12 may 2022");
menu();
modal();
validate();
tabs();
slider();
calc();
getSend();
sendForm({ formId: "form1" });
sendForm({ formId: "form2" });
sendForm({ formId: "form3" });
